package com.amicusearch.etl.utils.states.fl


object FLCourtMetadata {

  val countyCourtToCircut: Map[String, String] = Map(
    "Escambia County" -> "circuit_1",
    "Okaloosa County" -> "circuit_1",
    "Santa Rosa County" -> "circuit_1",
    "Walton County" -> "circuit_1",
    "Franklin County" -> "circuit_2",
    "Gadsden County" -> "circuit_2",
    "Jefferson County" -> "circuit_2",
    "Leon County" -> "circuit_2",
    "Liberty County" -> "circuit_2",
    "Wakulla County" -> "circuit_2",
    "Columbia County" -> "circuit_3",
    "Dixie County" -> "circuit_3",
    "Hamilton County" -> "circuit_3",
    "Lafayette County" -> "circuit_3",
    "Madison County" -> "circuit_3",
    "Suwannee County" -> "circuit_3",
    "Taylor County" -> "circuit_3",
    "Clay County" -> "circuit_4",
    "Duval County" -> "circuit_4",
    "Nassau County" -> "circuit_4",
    "Citrus County" -> "circuit_5",
    "Hernando County" -> "circuit_5",
    "Lake County" -> "circuit_5",
    "Marion County" -> "circuit_5",
    "Sumter County" -> "circuit_5",
    "Pasco County" -> "circuit_6",
    "Pinellas County" -> "circuit_6",
    "Flagler County" -> "circuit_7",
    "Putnam County" -> "circuit_7",
    "St. Johns County" -> "circuit_7",
    "Volusia County" -> "circuit_7",
    "Alachua County" -> "circuit_8",
    "Baker County" -> "circuit_8",
    "Bradford County" -> "circuit_8",
    "Gilchrist County" -> "circuit_8",
    "Levy County" -> "circuit_8",
    "Union County" -> "circuit_8",
    "Orange County" -> "circuit_9",
    "Osceola County" -> "circuit_9",
    "Hardee County" -> "circuit_10",
    "Highlands County" -> "circuit_10",
    "Polk County" -> "circuit_10",
    "Miami-Dade County" -> "circuit_11",
    "DeSoto County" -> "circuit_12",
    "Manatee County" -> "circuit_12",
    "Sarasota County" -> "circuit_12",
    "Hillsborough County" -> "circuit_13",
    "Bay County" -> "circuit_14",
    "Calhoun County" -> "circuit_14",
    "Gulf County" -> "circuit_14",
    "Holmes County" -> "circuit_14",
    "Jackson County" -> "circuit_14",
    "Washington County" -> "circuit_14",
    "Palm Beach County" -> "circuit_15",
    "Monroe County" -> "circuit_16",
    "Broward County" -> "circuit_17",
    "Brevard County" -> "circuit_18",
    "Seminole County" -> "circuit_18",
    "Indian River County" -> "circuit_19",
    "Martin County" -> "circuit_19",
    "Okeechobee County" -> "circuit_19",
    "St. Lucie County" -> "circuit_19",
    "Charlotte County" -> "circuit_20",
    "Collier County" -> "circuit_20",
    "Glades County" -> "circuit_20",
    "Hendry County" -> "circuit_20",
    "Lee County" -> "circuit_20",
  )

  val circuitToDistrict: Map[String, String] = Map(
    "circuit_1" -> "district_1",
    "circuit_2" -> "district_1",
    "circuit_3" -> "district_1",
    "circuit_4" -> "district_5",
    "circuit_5" -> "district_5",
    "circuit_6" -> "district_2",
    "circuit_7" -> "district_5",
    "circuit_8" -> "district_1",
    "circuit_9" -> "district_6",
    "circuit_10" -> "district_6",
    "circuit_11" -> "district_3",
    "circuit_12" -> "district_2",
    "circuit_13" -> "district_2",
    "circuit_14" -> "district_1",
    "circuit_15" -> "district_4",
    "circuit_16" -> "district_3",
    "circuit_17" -> "district_4",
    "circuit_18" -> "district_5",
    "circuit_19" -> "district_4",
    "circuit_20" -> "district_6",
  )

  val districtToSupreme: Map[String, String] = Map(
    "district_1" -> "florida_supreme_court",
    "district_2" -> "florida_supreme_court",
    "district_3" -> "florida_supreme_court",
    "district_4" -> "florida_supreme_court",
    "district_5" -> "florida_supreme_court",
    "district_6" -> "florida_supreme_court",
  )


}
