version: '3.5'

services:

  amicusearch-server:
    container_name: amicusearch-server
    image: amicusearch-ml-server:latest
    depends_on:
      - pgvector
    ports:
      - "5000:5000"

  pgvector:
    container_name: pgvector
    image: ankane/pgvector
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

networks:
  default:
    name: local