# circleci config that runs scala sbt tests

version: 2.1
_common:
  cache_moneys: &cache_moneys
    keys:
      - v1-dependencies-{{ checksum "build.sbt" }}
      - v1-dependencies-
  install_aws_cli: &install_aws_cli
    name: install aws-cli
    command: |
      sudo apt-get update && sudo apt-get install -y curl
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      sudo apt-get clean && sudo apt-get autoclean
      sudo apt-get install less
      mkdir ~/.aws && touch ~/.aws/config
      echo -e "[default]\n" \
              "region = us-west-2\n" \
              "output = json\n" \
              "credentials_source = Environment\n" \
              "role_session_name = CCISession\n" > ~/.aws/config
jobs:
  test:
    docker:
      - image: cimg/openjdk:8.0.362
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache: *cache_moneys
      - run:
          name: run_tests
          command: sbt test
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.sbt" }}
  deploy:
    docker:
      - image: cimg/openjdk:8.0.362
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache: *cache_moneys
      - run: *install_aws_cli
      - run:
          name: sbt assembly
          command: sbt assembly
      - run:
          name: copy jars to s3
          command: |
            aws s3 cp target/scala-2.13/AmicusearchETL.jar s3://amicusearch/etl/AmicusearchETL.jar
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.sbt" }}


workflows:
  build-test-deploy:
    jobs:
      - test
      - deploy:
          requires:
              - test
          filters:
              branches:
                only: master