package com.amicusearch.etl.datatypes.courtlistener.transforms

case class OpinionLtree(court_id: String,
                        court_citation_string: Option[String],
                        court_short_name: Option[String],
                        court_full_name: Option[String],
                        docket_id: String,
                        docket_number: Option[String],
                        docket_number_core: Option[String],
                        case_name_short: Option[String],
                        case_name: String,
                        case_name_full: Option[String],
                        slug: String,
                        region_partition: Option[String],
                        cluster_id: String,
                        date_filed: String,
                        scdb_id: Option[String],
                        headnotes: Option[String],
                        summary: Option[String],
                        citation_count: Option[String],
                        precedential_status: Option[String],
                        opinion_id: String,
                        plain_text: Option[String],
                        volume: Option[String],
                        reporter: Option[String],
                        page: Option[String],
                        cite_type: Option[String],

                        ltree: Option[String])
